model:
  model_name: &vit ViT-B-32
  pretrained: &pretrain laion2b_s34b_b79k
  output_dict: True
tokenizer: 
  model_name: *vit
dataset:
  train:
    name: &clip_class CLIPMultiTaskDataset
    params:
      dataset: data/processed/normal/artgraph_clip_multitask/train.csv
      img_dir: &images data/raw/images-resized
      tasks: &tasks [style, genre]
      sources:
        style: &style_source data/processed/styles.csv
        genre: &genre_source data/processed/genres.csv
      preprocess:
        name: &clip clip
        params: 
          model_name: *vit
          pretrained: *pretrain
      preprocess_classes:
        RandomWordAug:
          action: delete
          aug_p: 0.4
        SynonymAug:
          aug_src: wordnet
          aug_p: 0.4
  val:
    name: *clip_class
    params:
      dataset: data/processed/normal/artgraph_clip_multitask/val.csv
      img_dir: *images
      tasks: *tasks
      sources:
        style: *style_source
        genre: *genre_source
      preprocess:
        name: *clip
        params: 
          model_name: *vit
          pretrained: *pretrain
  test:
    name: ImageTextMultiTaskDataset
    params:
      dataset: data/processed/normal/artgraph_clip_multitask/test.csv
      img_dir: *images
      tasks: *tasks
      preprocess:
        name: *clip
        params:
          model_name: *vit
          pretrained: *pretrain
dataloader:
  batch_size: 32
  shuffle: True
  drop_last: False
  num_workers: 8
criterion:
  style:
    name: CLIPImageTextLoss
    params:
      return_logits: True
  genre:
    name: CLIPImageTextLoss
    params:
      return_logits: True
optimizer:
  name: Adam
  params:
    lr: 1e-5
scheduler:
  name: HuggingFaceCosineScheduler
  params:
    num_warmup_steps: 1000
early_stop:
  name: EarlyStopping
  params:
    verbose: True
    patience: 10
metrics:
  style:
    top1:
      name: Accuracy
      params:
        task: &task multiclass
        num_classes: 32
        top_k: 1
    top2:
      name: Accuracy
      params:
        task: *task
        num_classes: 32
        top_k: 2
    f1score:
      name: F1Score
      params:
        task: *task
        num_classes: 32
        average: macro
  genre: 
    top1:
      name: Accuracy
      params:
        task: *task
        num_classes: 18
        top_k: 1
    top2:
      name: Accuracy
      params:
        task: *task
        num_classes: 18
        top_k: 2
    f1score:
      name: F1Score
      params:
        task: *task
        num_classes: 18
        average: macro
device: cuda
out_dir: models/multitask/normal_clip_fine_tunining_wikipedia
warmup: 5
num_epochs: 50
bar: True
key: summary
task: *tasks
lambda:
  style: 0.5
  genre: 0.5