
data:
  root: data/external/artgraph2bestemotions
  vis_feats_root: /home/raffaele/ext/contrastive-artwork-classification/visual_embeddings
  label_feats_root: /home/raffaele/ext/contrastive-artwork-classification/data/label_embeddings
pruner:
  mapping: data/external/artgraph2bestemotions/mapping/artwork_entidx2name.csv
  source: data/processed/normal/artgraph_clip/train.csv
  mapping_kwargs: 
    names: [idx, name]
  sample: .3
  random_state: 42
out_dir: data/processed/graph/0_1