#!/bin/bash
sbatch -o ./outs/1_0/normal_clip_graph_resgated2.out -e ./outs/1_0/normal_clip_graph_resgated2.out -job-name 1_0_resgated ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/1_0/resgated/normal_clip_graph_resgated2.yaml" --graph
sbatch -o ./outs/1_0/normal_clip_graph_resgated3.out -e ./outs/1_0/normal_clip_graph_resgated3.out -job-name 1_0_resgated ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/1_0/resgated/normal_clip_graph_resgated3.yaml" --graph
sbatch -o ./outs/1_0/normal_clip_graph_resgated2_tanh.out -e ./outs/1_0/normal_clip_graph_resgated2_tanh.out -job-name 1_0_resgated ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/1_0/resgated/normal_clip_graph_resgated2_tanh.yaml" --graph
sbatch -o ./outs/1_0/normal_clip_graph_resgated3_tanh.out -e ./outs/1_0/normal_clip_graph_resgated3_tanh.out -job-name 1_0_resgated ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/1_0/resgated/normal_clip_graph_resgated3_tanh.yaml" --graph
sbatch -o ./outs/1_0/normal_clip_graph_sage3.out -e ./outs/1_0/normal_clip_graph_sage3.out -job-name 1_0_sage ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/1_0/sage/normal_clip_graph_sage3.yaml" --graph
sbatch -o ./outs/1_0/normal_clip_graph_sage2.out -e ./outs/1_0/normal_clip_graph_sage2.out -job-name 1_0_sage ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/1_0/sage/normal_clip_graph_sage2.yaml" --graph
sbatch -o ./outs/1_0/normal_clip_graph_transformer3.out -e ./outs/1_0/normal_clip_graph_transformer3.out -job-name 1_0_transformer ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/1_0/transformer/normal_clip_graph_transformer3.yaml" --graph
sbatch -o ./outs/1_0/normal_clip_graph_transformer2.out -e ./outs/1_0/normal_clip_graph_transformer2.out -job-name 1_0_transformer ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/1_0/transformer/normal_clip_graph_transformer2.yaml" --graph
sbatch -o ./outs/1_0/normal_clip_graph_gat2.out -e ./outs/1_0/normal_clip_graph_gat2.out -job-name 1_0_gat ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/1_0/gat/normal_clip_graph_gat2.yaml" --graph
sbatch -o ./outs/1_0/normal_clip_graph_gat3.out -e ./outs/1_0/normal_clip_graph_gat3.out -job-name 1_0_gat ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/1_0/gat/normal_clip_graph_gat3.yaml" --graph