model:
  model_name: ViT-B-32
  pretrained: laion2b_s34b_b79k
tokenizer: ViT-B-32
labels:
  in_dir: data/external/artgraph2bestemotions/mapping
  exceptions: [artwork, rel, relidx2relname.csv]
  mapping:
    training: training_node
dataloader:
  batch_size: 128
  drop_last: False
  shuffle: False
out_dir: /leonardo_scratch/fast/IscrC_DIANA/ext/contrastive-artwork-classification/data/label_embeddings
device: cuda
source:
  style: data/processed/styles_mistral.csv
  genre: data/processed/genres_mistral.csv