dataset:
  test:
    name: ImageTextDatset
    params:
      dataset: data/processed/normal/artgraph_clip/test.csv
      img_dir: data/raw/images-resized
      preprocess: 
        name: Compose
        params:
          Resize:
            size: 224
            interpolation: 3
            antialias: True
          CenterCrop:
            size: [224, 224]
          ToTensor: None
          Normalize:
            mean: [0.48145466, 0.4578275, 0.40821073]
            std: [0.26862954, 0.26130258, 0.27577711]
dataloader:
  batch_size: 128
  num_workers: 8
  drop_last: False
  shuffle: True
model:
  model_name: &vit ViT-B-32
  pretrained: laion2b_s34b_b79k
tokenizer: 
  model_name: *vit
metrics:
  top1:
    name: Accuracy
    params:
      task: &task multiclass
      num_classes: 32
      top_k: 1
  top2:
    name: Accuracy
    params:
      task: *task
      num_classes: 32
      top_k: 2
  f1score:
    name: F1Score
    params:
      task: *task
      num_classes: 32
      average: macro
bar: True
device: cuda
out_dir: models/normal_clip_no_training_mistral_prototype
class_source: data/processed/styles_mistral_prototype.csv
key: style
