#!/bin/bash

#SBATCH -A IscrC_DIANA
#SBATCH -p boost_usr_prod
#SBATCH --qos boost_qos_dbg
#SBATCH --time 00:30:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1
#SBATCH --mem=123000
#SBATCH --exclusive
#SBATCH --job-name=test
#SBATCH --out=outs/test.out
#SBATCH --err=outs/test.out

srun ./slurms/baselines/no_training/exe $@