model:
  model_name: &vit ViT-B-32
  pretrained: &pretrain laion2b_s34b_b79k
  output_dict: True
tokenizer: 
  model_name: *vit
dataset:
  train:
    name: &clip_class CLIPDataset
    params:
      dataset: data/processed/normal/artgraph_clip/train.csv
      img_dir: &images data/raw/images-resized
      styles: &styles data/processed/styles_naive.csv
      preprocess:
        name: &clip clip
        params: 
          model_name: *vit
          pretrained: *pretrain
      preprocess_classes:
        RandomWordAug:
          action: delete
          aug_p: 0.4
        SynonymAug:
          aug_src: wordnet
          aug_p: 0.4
  val:
    name: *clip_class
    params:
      dataset: data/processed/normal/artgraph_clip/val.csv
      img_dir: *images
      styles: *styles
      preprocess:
        name: *clip
        params: 
          model_name: *vit
          pretrained: *pretrain
  test:
    name: ImageTextDatset
    params:
      dataset: data/processed/normal/artgraph_clip/test.csv
      img_dir: *images
      preprocess: 
        name: *clip
        params:
          model_name: *vit
          pretrained: *pretrain
dataloader:
  batch_size: 32
  shuffle: True
  drop_last: False
  num_workers: 8
criterion:
  name: CLIPImageTextLoss
  params:
    return_logits: True
optimizer:
  name: Adam
  params:
    lr: 1e-5
scheduler:
  name: HuggingFaceCosineScheduler
  params:
    num_warmup_steps: 1000
early_stop:
  name: EarlyStopping
  params:
    verbose: True
    patience: 10
metrics:
  top1:
    name: Accuracy
    params:
      task: &task multiclass
      num_classes: 32
      top_k: 1
  top2:
    name: Accuracy
    params:
      task: *task
      num_classes: 32
      top_k: 2
  f1score:
    name: F1Score
    params:
      task: *task
      num_classes: 32
      average: macro
device: cuda
out_dir: models/normal_clip_fine_tuning_naive
warmup: 5
num_epochs: 50
bar: True
class_source: *styles
class_key: summary
    