#!/bin/bash
sbatch -o ./outs/0_5/normal_clip_graph_resgated2.out -e ./outs/0_5/normal_clip_graph_resgated2.out --job-name 0_5_resgated ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/0_5/resgated/normal_clip_graph_resgated2.yaml" --graph
sbatch -o ./outs/0_5/normal_clip_graph_resgated3.out -e ./outs/0_5/normal_clip_graph_resgated3.out --job-name 0_5_resgated ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/0_5/resgated/normal_clip_graph_resgated3.yaml" --graph
sbatch -o ./outs/0_5/normal_clip_graph_resgated2_tanh.out -e ./outs/0_5/normal_clip_graph_resgated2_tanh.out --job-name 0_5_resgated ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/0_5/resgated/normal_clip_graph_resgated2_tanh.yaml" --graph
sbatch -o ./outs/0_5/normal_clip_graph_resgated3_tanh.out -e ./outs/0_5/normal_clip_graph_resgated3_tanh.out --job-name 0_5_resgated ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/0_5/resgated/normal_clip_graph_resgated3_tanh.yaml" --graph
sbatch -o ./outs/0_5/normal_clip_graph_sage3.out -e ./outs/0_5/normal_clip_graph_sage3.out --job-name 0_5_sage ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/0_5/sage/normal_clip_graph_sage3.yaml" --graph
sbatch -o ./outs/0_5/normal_clip_graph_sage2.out -e ./outs/0_5/normal_clip_graph_sage2.out --job-name 0_5_sage ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/0_5/sage/normal_clip_graph_sage2.yaml" --graph
sbatch -o ./outs/0_5/normal_clip_graph_transformer3.out -e ./outs/0_5/normal_clip_graph_transformer3.out --job-name 0_5_transformer ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/0_5/transformer/normal_clip_graph_transformer3.yaml" --graph
sbatch -o ./outs/0_5/normal_clip_graph_transformer2.out -e ./outs/0_5/normal_clip_graph_transformer2.out --job-name 0_5_transformer ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/0_5/transformer/normal_clip_graph_transformer2.yaml" --graph
sbatch -o ./outs/0_5/normal_clip_graph_gat2.out -e ./outs/0_5/normal_clip_graph_gat2.out --job-name 0_5_gat ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/0_5/gat/normal_clip_graph_gat2.yaml" --graph
sbatch -o ./outs/0_5/normal_clip_graph_gat3.out -e ./outs/0_5/normal_clip_graph_gat3.out --job-name 0_5_gat ./slurms/proposed_model/launch --parameters="./configs_cineca/proposed_model/0_5/gat/normal_clip_graph_gat3.yaml" --graph