model:
  visual:
    model_name: ViT-B-32
    pretrained: laion2b_s34b_b79k
    output_dict: true
  gnn:
    name: GraphSAGE
    params:
      in_channels: 512
      hidden_channels: 512
      num_layers: 3
      dropout: 0.25
      act: LeakyReLU
      act_kwargs:
        negative_slope: 0.2
      norm: LayerNorm
      norm_kwargs:
        mode: node
        affine: false
  params:
    target_node_t: genre
    use_logit_scale: true
dataset:
  train:
    name: ImageGraphDataset
    params:
      dataset: data/processed/normal/artgraph_clip_genre/train.csv
      img_dir: data/raw/images-resized
      mapping_kwargs:
        names:
        - idx
        - genre
      preprocess:
        name: clip
        params:
          model_name: ViT-B-32
          pretrained: laion2b_s34b_b79k
      graph_class_mapping: data/external/artgraph2bestemotions/mapping/genre_entidx2name.csv
      mapping_target_col: genre
  val:
    name: ImageGraphDataset
    params:
      dataset: data/processed/normal/artgraph_clip_genre/val.csv
      img_dir: data/raw/images-resized
      mapping_kwargs:
        names:
        - idx
        - genre
      preprocess:
        name: clip
        params:
          model_name: ViT-B-32
          pretrained: laion2b_s34b_b79k
      graph_class_mapping: data/external/artgraph2bestemotions/mapping/genre_entidx2name.csv
      mapping_target_col: genre
  test:
    name: ImageTextDatset
    params:
      dataset: data/processed/normal/artgraph_clip_genre/test.csv
      img_dir: data/raw/images-resized
      preprocess:
        name: clip
        params:
          model_name: ViT-B-32
          pretrained: laion2b_s34b_b79k
dataloader:
  batch_size: 256
  shuffle: true
  drop_last: false
  num_workers: 8
criterion:
  name: CLIPImageGraphLoss
  params:
    return_logits: true
optimizer:
  name: Adam
  params:
    lr: 1e-05
scheduler:
  name: HuggingFaceCosineScheduler
  params:
    num_warmup_steps: 1000
early_stop:
  name: EarlyStopping
  params:
    verbose: true
    patience: 10
metrics:
  top1:
    name: Accuracy
    params:
      task: multiclass
      num_classes: 18
      top_k: 1
  top2:
    name: Accuracy
    params:
      task: multiclass
      num_classes: 18
      top_k: 2
  f1score:
    name: F1Score
    params:
      task: multiclass
      num_classes: 18
      average: macro
device: cuda
out_dir: models/proposed/genre/normal_clip_graph_gcn3
clean_out_dir: true
warmup: 10
num_epochs: 50
bar: true
class_source:
  f: data/processed/graph/0_5/train_graph.pt
  map_location: cuda
