#!/bin/bash

#SBATCH -A IscrC_DIANA
#SBATCH -p boost_usr_prod
#SBATCH --qos boost_qos_lprod
#SBATCH --time 4-00:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1
#SBATCH --mem=123000
#SBATCH --exclusive
#SBATCH --job-name=fine_tuning
#SBATCH --out=outs/fine_tuning.out
#SBATCH --err=outs/fine_tuning.out

srun ./slurms/baselines/fine_tuning/exe $@